#!/usr/bin/env node
/**
 * WRITES REVIEW.md, the review packet for a non-programmer reader. Every section is READ from the
 * committed artifacts (clauses.json, register.json, ambiguities.json, FINDINGS.md, and one run of
 * the interpreter on empty facts) and rendered; nothing here restates a clause, a row, an
 * ambiguity or a finding in its own words, so the packet cannot disagree with what it reviews.
 * Re-run after any change to those files. No analysis is added.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { interpret, loadRegister } from '../_interpreter/interpret.mjs';

const HERE = new URL('.', import.meta.url).pathname;
const j = (f) => JSON.parse(readFileSync(`${HERE}${f}`, 'utf8'));
const clauses = j('clauses.json').clauses;
const register = loadRegister(`${HERE}register.json`);
const amb = j('ambiguities.json').ambiguities;
const findings = readFileSync(`${HERE}FINDINGS.md`, 'utf8');
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ');
const TIER_ORDER = { scope: 0, fi: 1, telco: 2, consumer: 3, process: 4, none: 5 };
const DUTY = { fi: 'the responsible FI', telco: 'the responsible Telco', account_holder: 'the account holder', account_user: 'the account user', none: 'nobody (scope, definition or allocation)' };
const TIER = { scope: 'scope', fi: 'FI tier', telco: 'Telco tier', consumer: 'consumer outcome', process: 'Section 7 workflow', none: 'none (no result)' };

let md = `# Review packet: the Shared Responsibility Framework register

For a reviewer who does not read code. Generated by \`build-review.mjs\` from the committed
register files on branch \`session/srf-corpus\`; every table below is read from them, not
retyped. The register encodes the MAS/IMDA **Guidelines on Shared Responsibility Framework**
(issued 24 October 2024, effective 16 December 2024) and the paragraphs of the **E-Payments User
Protection Guidelines** (amended 24 October 2024) that the SRF incorporates. Sources and digests:
\`SOURCES.md\`. Findings: \`FINDINGS.md\` (copied in at section 4).

Two words used throughout. A clause's **disposition** says what kind of thing a machine may do
with it: MECHANICAL (evaluate against recorded facts), CONDITIONAL (an obligation that arises only
on a precondition; \`not_applicable\` means it never arose, which is not a pass), DERIVED
(composes other clauses' results), JUDGMENT (taken as a person's assessment, never inferred),
DEFINITIONAL (supplies a meaning, produces no result), INSTRUCTION (directs an act, produces no
result). A record's **waiting** value says what an undetermined result is waiting on: a fact, a
judgment, a meaning, or another clause.

## Contents

1. Every clause: ID, duty holder, tier, plain-English restatement, verbatim source text
2. The Section 6 waterfall table (36 rows), with the two rows that reach the account holder
3. The ambiguity register in full (30 entries; A3 and A5 are wired guards)
4. Findings F-01 to F-20, copied from FINDINGS.md
5. What happens on empty facts

## 1. Every clause

${clauses.length} clauses, in the register's evaluation order (the order of the waterfall: scope,
FI tier, Telco tier, consumer outcome, then the workflow; clauses with no result sit beside the
clauses that consume their meaning). **Plain-English restatement** is the clause's \`assertion\`
field; **Source text** is the \`text_en\` field, quoted from the retrieved PDF, with its locator.

`;
const byId = Object.fromEntries(clauses.map((c) => [c.id, c]));
const order = register.clauses.map((c) => c.id);
md += '| # | Clause ID | Duty holder | Tier | Disposition | Plain-English restatement | Source text (verbatim) and locator |\n|---|---|---|---|---|---|---|\n';
order.forEach((id, i) => {
  const c = byId[id];
  md += `| ${i + 1} | \`${c.id}\` | ${DUTY[c.duty_holder]} | ${TIER[c.tier]} | ${c.disposition} | ${cell(c.assertion)} | "${cell(c.text_en)}" (${cell(c.source_locator)}) |\n`;
});

// ─── 2. the waterfall table ────────────────────────────────────────────────────────────────────
const outcomeClause = register.clauses.find((c) => c.id === 'srf/6.7/outcome');
const rows = outcomeClause.evaluate.rows;
const AH = rows.filter((r) => r.outcome === 'account_holder_bears');
md += `
## 2. The waterfall: \`srf/6.7/outcome\`

The consumer outcome is a decision table over three inputs, evaluated in this order: **scope**
(\`srf/7.1.1/relevant-claim\`: is this a relevant claim under the SRF at all), the **FI tier**
(\`srf/6/fi-tier\`: does the responsible FI bear the loss under 6.2 or 6.3), and the **Telco tier**
(\`srf/6.4/telco-bears\`: does the responsible Telco bear it under 6.4 to 6.6). Every combination
of the three inputs is a row; there are ${rows.length} (${outcomeClause.evaluate.cross_product} declared), and a
combination with no row is an error, never a default.

The two rows marked **▶** are the only ways the account holder comes to bear the loss. Both
require, on the two prior tiers, **affirmative findings of non-liability**, never an absence:

`;
for (const r of AH) {
  md += `- **▶ scope = \`${r.match.scope}\`, FI tier = \`${r.match.fi_tier}\`, Telco tier = \`${r.match.telco_tier}\` → \`account_holder_bears\`.** `;
  md += `Required first: (i) scope closed \`relevant_claim\` on four affirmative findings (responsible FI, not a card transaction, protected account, seemingly authorised transaction); (ii) the FI tier closed \`fi_not_liable\`, which needs 6.2 to have closed \`fi_not_liable_under_6.2\` (five affirmative non-breach findings on the 4.2 duties, or a breach the loss affirmatively did not arise from) AND 6.3 to have closed \`not_satisfied\` (an affirmative denial of fraud/negligence and MAS non-compliance, or of causation); `;
  md += r.match.telco_tier === 'not_applicable'
    ? `(iii) the Telco tier answered \`not_applicable\` because 7.7 affirmatively found the scam was **not** perpetrated through SMS (a recorded contact platform other than SMS, never an absent one).${r.note ? ' Note on the row: ' + r.note : ''}\n`
    : `(iii) the Telco tier closed \`telco_not_liable\` on affirmative findings: the FI complied with all of 4.2 and the three 5.2 duties were affirmatively not breached, or a breach was established and causation or 6.6 was affirmatively denied.${r.note ? ' Note on the row: ' + r.note : ''}\n`;
}
md += `
A duty that never arose (for example, no digital token was activated, so 4.2.1 had nothing to
require) counts toward "complied with all" only under a supplied resolution of ambiguity A3; with
A3 unresolved the FI tier is undetermined and the waterfall stops there.

| # | Scope | FI tier | Telco tier | Outcome | Note |
|---|---|---|---|---|---|
`;
rows.forEach((r, i) => {
  const mark = r.outcome === 'account_holder_bears' ? '**▶ ' : '';
  const end = r.outcome === 'account_holder_bears' ? '**' : '';
  const note = [r.note, r.$decided_on_absence ? `Decided with an undetermined input, by rule: ${r.$decided_on_absence}` : null].filter(Boolean).join(' ');
  md += `| ${i + 1} | ${mark}${r.match.scope}${end} | ${mark}${r.match.fi_tier}${end} | ${mark}${r.match.telco_tier}${end} | ${mark}\`${r.outcome}\`${end} | ${cell(note)} |\n`;
});

// ─── 3. ambiguities ────────────────────────────────────────────────────────────────────────────
const wired = new Set(['A3', 'A5']);
md += `
## 3. The ambiguity register

${amb.length} entries. None is resolved: choosing a reading is an institutional decision, and the
register takes it as an input. Two entries are **wired guards**: where a clause's result turns on
them, the clause is undetermined until the resolution is supplied (A3 under
\`resolutions.A3_not_applicable_duty\`, A5 under \`resolutions.A5_filter_duty_reading\`). The rest
are recorded, and the register evaluates one reading, named in each entry.

`;
for (const a of amb) {
  md += `### ${a.id}${wired.has(a.id) ? ' — WIRED GUARD' : ''}: on \`${a.clause_id}\`\n\n**Question.** ${a.question}\n\n**Readings the words permit.**\n`;
  for (const r of a.competing_readings) md += `- *${r.reading}.* ${r.basis}\n`;
  md += `\n**Textual basis.** ${a.textual_basis}\n\n**What turns on it.** ${a.materiality}\n\n**What the register evaluates.** ${a.evaluated_reading}\n\n**Resolution required:** ${a.required_resolution === null ? 'none supplied; open.' : a.required_resolution}\n\n`;
}

// ─── 4. findings ───────────────────────────────────────────────────────────────────────────────
const start = findings.indexOf('## Numbered findings');
const end = findings.indexOf('## What this does not cover');
md += `## 4. Findings F-01 to F-20, copied from FINDINGS.md\n\n` + findings.slice(start + '## Numbered findings'.length, end).trim().replace(/^\*\*F-/gm, '**F-') + '\n\n';

// ─── 5. empty facts ────────────────────────────────────────────────────────────────────────────
const out = interpret(register, {}, {});
const evaluable = Object.values(out).filter((r) => 'result' in r);
const undet = evaluable.filter((r) => ['undetermined', 'not_assessed', 'missing_operand', 'no_end_event', 'no_candidate'].includes(r.result));
const decided = evaluable.length - undet.length;
const byWaiting = {};
for (const r of undet) byWaiting[r.waiting] = (byWaiting[r.waiting] ?? 0) + 1;
md += `## 5. What happens on empty facts

Run with no facts at all (measured by this script, at generation): of ${Object.keys(out).length} clauses,
${Object.keys(out).length - evaluable.length} produce no result by category (definitions and instructions) and
**${evaluable.length} are evaluable; every one of the ${evaluable.length} comes back undetermined and ${decided} decide anything**
(${Object.entries(byWaiting).map(([k, v]) => `${v} waiting on a ${k}`).join(', ')}). No duty is read as discharged, no account is read
as protected or unprotected, no scam is read as in or out of scope, and the waterfall does not
start: an FI, a Telco or an account holder is found liable or not liable only from facts and
assessments someone recorded, and a claim about which nothing is recorded is a claim about which
the register says nothing.
`;
writeFileSync(`${HERE}REVIEW.md`, md);
console.log(`REVIEW.md: ${clauses.length} clauses, ${rows.length} rows, ${amb.length} ambiguities, empty facts ${evaluable.length} evaluable / ${undet.length} undetermined / ${decided} decided`);
