#!/usr/bin/env node
/**
 * Three worked cases. Facts first; every result below is computed by running the evaluator.
 *
 * NOT generated by _corpus/. That generator does not fit this domain, for two reasons stated in
 * FINDINGS.md and measured: it draws candidate values from a fact register this domain does not
 * have, and its explorer reads `v.result` from every emitted entry, which would record all 24
 * no-result-domain clauses as having a result of `undefined`.
 *
 * Case 2 turns on an UNGROUNDED term and is run twice, with and without a supplied meaning.
 */
import { evaluate, resultOf } from './evaluate.mjs';
const clone = (o) => JSON.parse(JSON.stringify(o));

const base = {
  claim: { type_claimed: 'direct', condition_class: 'orthopaedic', pre_existing_same_site: false,
           aggravation_issue_undeveloped: false, consequential_claimed: false,
           physical_injury_established: true, graver_condition_undeveloped: false },
  injury: { clear_cut_and_competent: 'affirmed', minor_and_lay_identifiable: 'denied',
            witnessed_or_prompt: true, fact_disputed: false },
  opinion: { present: 'CA-20 narrative', examined_or_treated: true, source_class: 'surgeon',
             diagnosis: 'closed fracture right femur', objective_findings: 'radiograph',
             relationship_opinion: 'caused by the fall', rationale_grade: 'affirmative_statement',
             negates_relationship: false, aggravation_duration_clear: true,
             rationale_sufficient_for_class: 'affirmed', psychiatrist_required_assessed: 'not_assessed' },
  file: { contrary_evidence: false },
  adjudicator: { development_complete: 'affirmed', difficulty_assessed: 'affirmed',
                 further_opinion_necessary: 'denied', adjudicable_on_present_opinion: 'affirmed',
                 opinions_approximately_equal: 'denied', all_evidence_carefully_evaluated: 'affirmed',
                 second_opinion_appropriate: 'denied', specialist_discussion_sufficient: 'not_assessed',
                 relative_probability_weighed: 'not_assessed', period_allowed_reasonable: 'affirmed' },
  acceptance: { accepted_as: 'direct', physical_injury_accepted: true, accepted_at: '2026-04-10T00:00:00Z' },
  exposure: {}, intervening: {}, consequential: {}, authorisation: { items: [] },
};

// CASE 1. A clear-cut traumatic injury. The waiver in 3c does not apply, so 3d does.
const c1 = { name: 'Clear-cut traumatic injury, fracture, opinion on file', facts: clone(base), res: {} };

// CASE 2. An occupational illness needing a rationalized opinion. THE OPERATIVE TERM IS UNGROUNDED.
const f2 = clone(base);
f2.claim.type_claimed = 'direct';
f2.claim.condition_class = 'pulmonary';
f2.injury.clear_cut_and_competent = 'denied';
f2.opinion.rationale_grade = 'detailed_rationale';
f2.opinion.specialist_credential = 'board_certified_pulmonary';
f2.opinion.specialist_opinion_at = '2026-04-01T00:00:00Z';
const c2 = { name: 'Occupational pulmonary claim: the requirement is a term the chapter never defines',
             facts: f2, res: {} };
// the same facts, with an institution having supplied a meaning
const c2b = { name: '...the same claim, with a meaning supplied for `rationalized medical opinion`',
              facts: clone(f2),
              res: { ungrounded_terms: { 'rationalized medical opinion': { accepts: ['detailed_rationale'] } } } };

// CASE 3. Aggravation of a pre-existing condition at the same site.
const f3 = clone(base);
f3.claim.type_claimed = 'aggravation';
f3.claim.pre_existing_same_site = true;
f3.opinion.aggravation_diagnosed_by = 'surgeon';
f3.opinion.aggravation_duration_clear = false;
f3.opinion.differentiates = true;
f3.opinion.rationale_grade = 'detailed_rationale';
f3.acceptance.accepted_as = 'temporary_aggravation';
const c3 = { name: 'Aggravation of a pre-existing condition, duration unclear', facts: f3, res: {} };

const pad = (s, n) => String(s).padEnd(n);
for (const c of [c1, c2, c2b, c3]) {
  console.log('\n' + '='.repeat(100));
  console.log(c.name);
  const supplied = c.res.ungrounded_terms ? Object.keys(c.res.ungrounded_terms).join(', ') : 'NONE';
  console.log(`  meanings supplied for ungrounded terms: ${supplied}`);
  console.log('='.repeat(100));
  const out = evaluate(c.facts, c.res);
  for (const [id, v] of Object.entries(out)) {
    if (!('result' in v)) continue;
    const tail = v.undetermined_because ? '   <- ' + v.undetermined_because
      : v.rests_on ? '   <- ' + v.rests_on + ': `' + v.term + '`'
      : v.definition_applied ? '   (definition applied: ' + v.definition_applied.split('/').slice(-2).join('/') + ')' : '';
    console.log('  ' + pad(id, 44) + pad(v.result, 18) + tail);
  }
  const refused = Object.entries(out).filter(([, v]) => !('result' in v));
  const by = {};
  for (const [, v] of refused) { const k = v.refused ?? v.no_result; by[k] = (by[k] || 0) + 1; }
  console.log('  ' + pad('NO RESULT DOMAIN, refused:', 44) + Object.entries(by).map(([k, v]) => `${v} ${k}`).join(', '));
}
